# Generated by Django 5.1.5 on 2025-01-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_blog_image_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_heading',
            field=models.CharField(max_length=100),
        ),
    ]
