# Generated by Django 5.1.5 on 2025-01-28 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_interactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='unlike_count',
        ),
    ]
