# Generated by Django 5.1.5 on 2025-02-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_blog_like_count_remove_blog_unlike_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
